const CNPJ_CORRETO = '18.596.101/0001-32';
const CNPJ_INCORRETO = '18.596.101/000-32';

const CD_FUNC_INCORRETO = '103';
const CD_FUNC = '101';

const USUARIO_INCORRETO = 'V103';
const USUARIO_CORRETO = 'V101';

const SENHA_ERRADA = '2'
const SENHA_CORRETA = '1';

module.exports = {
  CNPJ_CORRETO,
  CNPJ_INCORRETO,
  CD_FUNC,
  CD_FUNC_INCORRETO,
  USUARIO_CORRETO,
  USUARIO_INCORRETO,
  SENHA_CORRETA,
  SENHA_ERRADA
};